### ISSUE TITLE
Failed login handling issue

### ISSUE THREAD

**Issue by hossamefia** [Intechnity-com/OdooJsonRpcClient#81]
I am getting the following error on login
Am expecting failed log-in 

var loginResult = await odooClient.LoginAsync();

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at PortaCapena.OdooJsonRpcClient.OdooClient.<CallAndDeserializeAsync>d__49`1.MoveNext()

**Comment by Andres-98** [comment]
I have the same error
<img width="768" alt="image" src="https://github.com/Intechnity-com/OdooJsonRpcClient/assets/64283260/cf3ae2c4-1ed2-4e60-b855-7e7165147061">

**Comment by patricoos** [comment]
When odoo crashes, returns html. The error: "value: <. " is from <html>.  Check your environment, then login and password

**Comment by hossamefia** [comment]
Yes you are correct but it needs to be handled

**Comment by SlimAhmad** [comment]
@hossamefia   please how'd you resolve this issue
